### PR TITLE
Revert oauth impl - Commits 13ad6e2 and 41028c1 

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Fix master branch

## What
Revert the following changes 
- 13ad6e2 feat(auth): adding oauth proxy deploy (AEROGEAR-8987)¶
- 41028c1 fix(oauth): allow users with no namespace access to log in¶

## Why
Unfortunately, after OAuth impl the Service cannot so longer be called by the APP CR. 

## How
Reverting by git commands in order to solve the conflicts
- git revert 41028c19bd66ead73d27d47118359ee918bc8710
- git revert 13ad6e2cbc9752df79f42e2a67f471ffb9fe7b0b
- Keeping the changes of the Readme by cut and pasting the README and just removing the Oauth explanation

## Verification Steps
1. Install using this PR + the image `docker.io/cmacedo/mobile-security-service-operator:revert-oauth`
Screenshot 2019-05-12 at 09 56 09

2. Install all via `make create-all`
- Check that the operator and MSS project and DB is running
- Check that the configMap was created by the MSS
- Check that the DB is using the ConfigMap

Screenshot 2019-05-12 at 09 59 05
Screenshot 2019-05-12 at 09 58 54
Screenshot 2019-05-12 at 09 58 30
Screenshot 2019-05-12 at 09 58 24

3. Create a new namespace and install `oc new-project mobile-security-service-apps`  
4. Run`make create-app`
- Check that the configMap of this app was created 
- Check that it was created in the Service by accessing its UI and/or database and/or By postman

Screenshot 2019-05-12 at 10 02 02
Screenshot 2019-05-12 at 10 01 46

4. Run`make delete-app`
- Check that the ConfigMap was removed
- Check that the app was removed in the Service

Screenshot 2019-05-12 at 10 03 11
Screenshot 2019-05-12 at 10 03 04

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @laurafitzgerald,

Unfortunately, the Oauth impl is broken the main features which are bind/unbind the app which we need do the demo.  After looking at this implementation and read the Oauth [doc](https://github.com/openshift/oauth-proxy#delegate-authentication-and-authorization-to-openshift-for-infrastructure) and checking our projects  following some points.

1. It is missing to create the secret and/or add certs which will be used to do the authentication. See [here](https://github.com/search?l=Go&q=org%3Aintegr8ly+secret&type=Code)
2. The http/client need be setup to pass the secret or certs, etc ... in th requequests for them be authenticated. See [here](https://github.com/integr8ly/3scale-operator-old/blob/43abc73120c37cc4f221aaa59f3e8ee135e7a7ba/pkg/threescale/client.go#L273) and [here](
https://github.com/integr8ly/installation/blob/8464083b2c2735f058dc06a9537fe946ae624539/roles/launcher/tasks/provision-launcher.yml#L41)
3. The type impl here is

**Comment by davidffrench** [comment]
@camilamacedo86 Could you please setup a meeting today to discuss your comment above and how we can solve this issue.

**Comment by camilamacedo86** [comment]
HI @laurafitzgerald and @davidffrench, could you approve we move forward with the revert until we find the solution?

**Comment by davidffrench** [comment]
@camilamacedo86 If the work to fix this will be completed soon, I would rather hold off on reverting the changes. @laurafitzgerald I would like your input here.

**Comment by laurafitzgerald** [comment]
@davidffrench based on the investigation it is possible to go with option1 which we discussed. See notes in [the JIRA](https://issues.jboss.org/browse/AEROGEAR-8987?focusedCommentId=13732547&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13732547)
I'm progressing the inclusion of that in the operator now. If it's required to unblock Camila then we can merge this pr and I can cherrypick the commits into the new pr. If it's not required to unblock Camila then we could leave the commits in as we should have the new changes soon.

**Comment by camilamacedo86** [comment]
Hi @laurafitzgerald,

I am closing it since we decided to move forward with the fix instead of. If we change our minds we can re-opened.

**Pull request closed without merging**
