### PR TITLE
feat(operator): Changing scope for namespace

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
https://issues.jboss.org/browse/AEROGEAR-9089

## What
* Change the scope from cluster to namespace

## Verification Steps
PS.: Use the image `cmacedo/mobile-security-service-operator:AEROGEAR-9089` in DockerHub or create a new one based on this PR.

* Clone locally the PR
* Change the image in operator.yaml to `cmacedo/mobile-security-service-operator:AEROGEAR-9089`
* Update the clusterHost in the CR files
* Install all by `make create-all`
* Check that all is running perfect well
* Create a new namespace by `oc new-project myapp`
* Run `make create-app`
* Check that the app was bind and the configMap was created 

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

Screenshot 2019-04-30 at 16 37 45
Screenshot 2019-04-30 at 16 37 40
Screenshot 2019-04-30 at 16 37 17
Screenshot 2019-04-30 at 16 37 13

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@camilamacedo86 When I run `make create-app` I don't get a configmap created in the `myapp` namespace. Also when I tried to clear it I used `make delete-app` which delete the mss application. Could that be updated?

**Comment by camilamacedo86** [comment]
@laurafitzgerald I don't think so. Could you please check if you update the example CR to create the app with the clusterHost? We will remove that in the future, however, still needed for now.

**Comment by camilamacedo86** [comment]
Issue Found: We need to fix the rules for the operator and app cr in order to move forward with.

**Comment by camilamacedo86** [comment]
Ignore this pr. I am checking it better. I don't think nothing of this will be required

**Pull request closed without merging**
